apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-node-rc
  labels:
    app: chrome-node-rc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome-node-rc
  template:
    metadata:
      name: chrome-node-rc
      labels:
        app: chrome-node-rc
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: chrome-node-rc
          image: 'selenium/node-chrome-debug:3.141'
          ports:
            - containerPort: 5555
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: HUB_HOST
              value: 35.202.84.28
            - name: HUB_PORT
              value: '4444'
          resources:
            limits:
              memory: 1000Mi
              cpu: 500m
