apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: selenium-hub
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.226.102
  clusterIPs:
    - 34.118.226.102
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port0
      nodePort: 30569
      port: 4444
      protocol: TCP
      targetPort: 4444
    - name: port1
      nodePort: 30808
      port: 4443
      protocol: TCP
      targetPort: 4443
    - name: port2
      nodePort: 31562
      port: 4442
      protocol: TCP
      targetPort: 4442
  selector:
    app: selenium-hub
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.102.25.223




#apiVersion: v1
#kind: Service
#metadata:
#  name: selenium-hub
#  labels:
#    app: selenium-hub
#spec:
#  ports:
#    - port: 4444
#      targetPort: 4444
#      name: port0
#    - port: 4443
#      targetPort: 4443
#      name: port1
#    - port: 4442
#      targetPort: 4442
#      name: port2
#  selector:
#    app: selenium-hub
#  type: LoadBalancer
##  loadBalancerIP: 34.94.95.107
#
##status:
##  loadBalancer:
##    ingress:
##      - ip: 34.102.101.254
