apiVersion: v1
kind: Service
metadata:
  name: selenium-svc
  labels:
    app: selenium-svc
spec:
  clusterIP: 10.127.128.0
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32675
    port: 80
    protocol: TCP
    targetPort: 4444
  selector:
    app: selenium-hub
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.102.101.254
